basePath: /api/v1
definitions:
  models.Address:
    properties:
      city:
        type: string
      country:
        type: string
      created_at:
        type: string
      id:
        type: integer
      state:
        type: string
      street:
        type: string
      updated_at:
        type: string
      user_id:
        type: integer
      zip_code:
        type: string
    required:
    - city
    - country
    - state
    - street
    - zip_code
    type: object
  models.Cart:
    properties:
      checkout:
        type: boolean
      created_at:
        type: string
      deleted_at:
        type: string
      id:
        type: integer
      price:
        type: string
      product_id:
        type: integer
      quantity:
        type: integer
      total:
        type: string
      updated_at:
        type: string
      user_id:
        type: integer
    required:
    - id
    - price
    - product_id
    - quantity
    - user_id
    type: object
  models.ForgetPasswordRequest:
    properties:
      email:
        type: string
    required:
    - email
    type: object
  models.OTPData:
    properties:
      email:
        type: string
    required:
    - email
    type: object
  models.Product:
    properties:
      category:
        type: string
      created_at:
        type: string
      description:
        type: string
      id:
        type: integer
      image:
        type: string
      name:
        type: string
      price:
        type: number
      stock:
        type: integer
      updated_at:
        type: string
    type: object
  models.ResetPassword:
    properties:
      confirm_password:
        type: string
      email:
        $ref: '#/definitions/models.ForgetPasswordRequest'
      password:
        type: string
    required:
    - confirm_password
    - email
    - password
    type: object
  models.User:
    properties:
      address:
        items:
          $ref: '#/definitions/models.Address'
        type: array
      created_at:
        type: string
      email:
        type: string
      id:
        type: integer
      is_verified:
        type: boolean
      name:
        maxLength: 30
        minLength: 2
        type: string
      password:
        minLength: 6
        type: string
      phone:
        type: string
      refresh_token:
        type: string
      token:
        type: string
      updated_at:
        type: string
    required:
    - email
    - name
    - password
    - phone
    type: object
  models.UserLogin:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  models.UserRequest:
    properties:
      email:
        type: string
      name:
        maxLength: 30
        minLength: 2
        type: string
      password:
        minLength: 6
        type: string
      phone:
        type: string
    required:
    - email
    - name
    - password
    - phone
    type: object
  models.VerfiyOTP:
    properties:
      Email:
        $ref: '#/definitions/models.OTPData'
      code:
        type: string
    required:
    - Email
    - code
    type: object
  responsehandler.ErrorHandler:
    properties:
      error:
        type: boolean
      message:
        type: string
    type: object
  responsehandler.SuccessResponse:
    properties:
      data: {}
      message:
        type: string
      success:
        type: boolean
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a sample server using Echo.
  title: Ecommerce API Swagger
  version: "1.0"
paths:
  /address:
    post:
      consumes:
      - application/json
      description: Adds a new address to the user's profile
      parameters:
      - description: Address information
        in: body
        name: address
        required: true
        schema:
          $ref: '#/definitions/models.Address'
      produces:
      - application/json
      responses:
        "200":
          description: Success message with address updated confirmation
          schema:
            $ref: '#/definitions/responsehandler.SuccessResponse'
        "400":
          description: Invalid address input
          schema:
            $ref: '#/definitions/responsehandler.ErrorHandler'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/responsehandler.ErrorHandler'
      security:
      - ApiKeyAuth: []
      summary: Add a new address for the authenticated user
      tags:
      - address
  /address/{id}:
    delete:
      consumes:
      - application/json
      description: Removes a specified address associated with a user
      parameters:
      - description: Address information containing address Id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responsehandler.SuccessResponse'
        "400":
          description: Invalid input or deletion error
      summary: Delete a user's address
      tags:
      - addresses
    get:
      consumes:
      - application/json
      description: Retrieves a specific address associated with the authenticated
        user
      parameters:
      - description: Address ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: User Address
          schema:
            allOf:
            - $ref: '#/definitions/responsehandler.SuccessResponse'
            - properties:
                data:
                  $ref: '#/definitions/models.Address'
              type: object
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/responsehandler.ErrorHandler'
        "404":
          description: No data found
          schema:
            type: string
      summary: Get a user's address
      tags:
      - addresses
  /addresses:
    get:
      consumes:
      - application/json
      description: Retrieve all addresses for the authenticated user
      produces:
      - application/json
      responses:
        "200":
          description: User Address
          schema:
            allOf:
            - $ref: '#/definitions/responsehandler.SuccessResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/models.Address'
                  type: array
              type: object
        "500":
          description: Error message
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: Get user addresses
      tags:
      - addresses
  /auth/forget-password:
    post:
      consumes:
      - application/json
      description: Sends a one-time password to the user's email for password reset
      parameters:
      - description: Email address
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.ForgetPasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OTP sent successfully
          schema:
            $ref: '#/definitions/responsehandler.SuccessResponse'
        "400":
          description: Invalid email or OTP sending failed
          schema:
            $ref: '#/definitions/responsehandler.ErrorHandler'
        "404":
          description: User not found
          schema:
            $ref: '#/definitions/responsehandler.ErrorHandler'
      summary: Initiate password reset process
      tags:
      - auth
  /auth/reset-password:
    post:
      consumes:
      - application/json
      description: Resets a user's password after verification
      parameters:
      - description: Password reset details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.ResetPassword'
      produces:
      - application/json
      responses:
        "200":
          description: password updated successfully
          schema:
            $ref: '#/definitions/responsehandler.SuccessResponse'
        "400":
          description: invalid request, invalid input, or password didn't match
          schema:
            $ref: '#/definitions/responsehandler.ErrorHandler'
        "500":
          description: internal server error
          schema:
            $ref: '#/definitions/responsehandler.ErrorHandler'
      summary: Reset user password
      tags:
      - auth
  /auth/send-email-otp:
    post:
      consumes:
      - application/json
      description: Sends a one-time password to the user's email for verification
      produces:
      - application/json
      responses:
        "200":
          description: OTP sent successfully
          schema:
            $ref: '#/definitions/responsehandler.SuccessResponse'
        "400":
          description: OTP sending failed
          schema:
            $ref: '#/definitions/responsehandler.ErrorHandler'
      security:
      - ApiKeyAuth: []
      summary: Send email verification OTP
      tags:
      - auth
  /auth/verify-email-otp:
    post:
      consumes:
      - application/json
      description: Verifies the OTP sent to the user's email for email verification
      parameters:
      - description: Verification code
        in: body
        name: code
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OTP verified successfully
          schema:
            $ref: '#/definitions/responsehandler.SuccessResponse'
        "400":
          description: Error message
          schema:
            $ref: '#/definitions/responsehandler.ErrorHandler'
      security:
      - ApiKeyAuth: []
      summary: Verify email verification OTP
      tags:
      - auth
  /auth/verify-reset-otp:
    post:
      consumes:
      - application/json
      description: Verifies the OTP code sent to user's email for password reset
      parameters:
      - description: Email and OTP verification details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.VerfiyOTP'
      produces:
      - application/json
      responses:
        "200":
          description: OTP verified successfully
          schema:
            $ref: '#/definitions/responsehandler.SuccessResponse'
        "400":
          description: Invalid request, email address, OTP or code
          schema:
            $ref: '#/definitions/responsehandler.ErrorHandler'
      summary: Verify password reset OTP
      tags:
      - auth
  /buy-cart:
    get:
      consumes:
      - application/json
      description: Retrieve all items in the user's cart
      parameters:
      - description: User ID
        in: query
        name: user_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responsehandler.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responsehandler.ErrorHandler'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responsehandler.ErrorHandler'
      summary: Get items from cart
      tags:
      - cart
  /cart:
    delete:
      consumes:
      - application/json
      description: Remove a product from the user's cart
      parameters:
      - description: Product ID
        in: path
        name: product_id
        required: true
        type: integer
      - description: User ID
        in: path
        name: user_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responsehandler.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responsehandler.ErrorHandler'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responsehandler.ErrorHandler'
      summary: Remove product from cart
      tags:
      - cart
    get:
      consumes:
      - application/json
      description: Retrieve all items in the user's cart
      parameters:
      - description: User ID
        in: path
        name: user_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: List of Products in cart
          schema:
            allOf:
            - $ref: '#/definitions/responsehandler.SuccessResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/models.Cart'
                  type: array
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responsehandler.ErrorHandler'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responsehandler.ErrorHandler'
      summary: Get items from cart
      tags:
      - cart
    post:
      consumes:
      - application/json
      description: Add a product to the user's cart
      parameters:
      - description: Product ID
        in: path
        name: product_id
        required: true
        type: integer
      - description: User ID
        in: path
        name: user_id
        required: true
        type: integer
      - description: Cart object
        in: body
        name: cart
        required: true
        schema:
          $ref: '#/definitions/models.Cart'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responsehandler.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responsehandler.ErrorHandler'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responsehandler.ErrorHandler'
      summary: Add product to cart
      tags:
      - cart
  /login:
    post:
      consumes:
      - application/json
      description: User login
      parameters:
      - description: Login object
        in: body
        name: login
        required: true
        schema:
          $ref: '#/definitions/models.UserLogin'
      produces:
      - application/json
      responses:
        "200":
          description: User Response
          schema:
            allOf:
            - $ref: '#/definitions/responsehandler.SuccessResponse'
            - properties:
                data:
                  $ref: '#/definitions/models.User'
              type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Login
      tags:
      - auth
  /products:
    get:
      consumes:
      - application/json
      description: Search products by query (optional)
      parameters:
      - description: query string for searching products
        in: query
        name: query
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: List of products
          schema:
            allOf:
            - $ref: '#/definitions/responsehandler.SuccessResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/models.Product'
                  type: array
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responsehandler.ErrorHandler'
      summary: Get Products / Search products
      tags:
      - products
  /products/{id}:
    get:
      consumes:
      - application/json
      description: Retrieves a product from the database based on the provided ID
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Product
          schema:
            allOf:
            - $ref: '#/definitions/responsehandler.SuccessResponse'
            - properties:
                data:
                  $ref: '#/definitions/models.Product'
              type: object
        "400":
          description: Bad request - Invalid or missing product ID
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responsehandler.ErrorHandler'
      summary: Get product by ID
      tags:
      - products
  /signup:
    post:
      consumes:
      - application/json
      description: User signup
      parameters:
      - description: User object
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.UserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/responsehandler.SuccessResponse'
        "400":
          description: Validation error
          schema:
            $ref: '#/definitions/responsehandler.ErrorHandler'
        "409":
          description: User already exists
          schema:
            $ref: '#/definitions/responsehandler.ErrorHandler'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/responsehandler.ErrorHandler'
      summary: singup
      tags:
      - auth
swagger: "2.0"
