basePath: /api/v1
definitions:
  models.Address:
    properties:
      address:
        type: string
      city:
        type: string
      country:
        type: string
      created_at:
        type: string
      deleted_at:
        type: string
      state:
        type: string
      updated_at:
        type: string
      user_id:
        type: integer
      zip_code:
        type: string
    type: object
  models.Cart:
    properties:
      checkout:
        type: boolean
      created_at:
        type: string
      deleted_at:
        type: string
      id:
        type: integer
      price:
        type: string
      product_id:
        type: integer
      quantity:
        type: integer
      total:
        type: string
      updated_at:
        type: string
      user_id:
        type: integer
    type: object
  models.Order:
    properties:
      created_at:
        type: string
      deleted_at:
        type: string
      id:
        type: integer
      order_status:
        type: string
      product_id:
        type: integer
      quantity:
        type: integer
      total_price:
        type: number
      updated_at:
        type: string
      user_id:
        type: integer
    type: object
  models.User:
    properties:
      address:
        $ref: '#/definitions/models.Address'
      cart:
        items:
          $ref: '#/definitions/models.Cart'
        type: array
      created_at:
        type: string
      deleted_at:
        type: string
      email:
        type: string
      id:
        type: integer
      name:
        maxLength: 30
        minLength: 2
        type: string
      orders:
        items:
          $ref: '#/definitions/models.Order'
        type: array
      password:
        minLength: 6
        type: string
      phone:
        type: string
      refresh_token:
        type: string
      token:
        type: string
      updated_at:
        type: string
    required:
    - address
    - email
    - name
    - password
    - phone
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a sample server using Echo.
  title: Ecommerce API Swagger
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      description: User login
      parameters:
      - description: User object
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Login
      tags:
      - auth
  /signup:
    post:
      consumes:
      - application/json
      description: User signup
      parameters:
      - description: User object
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: singup
      tags:
      - auth
  /user/{id}:
    get:
      consumes:
      - application/json
      description: Get user by ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get a user
      tags:
      - users
  /verify-email:
    get:
      consumes:
      - application/json
      description: Verify email format
      parameters:
      - description: Email address
        in: query
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Verify Email
      tags:
      - auth
swagger: "2.0"
